#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#e78a4e'
TEXT='#d4be98'
INPUT='#d4be98'
WRONG='#ea6962'
VERIFYING='#a9b665'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$INPUT         \
--bshl-color=$INPUT          \
\
--screen 1                   \
--blur 8                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                \
