#!/bin/sh

# Gruvbox color palette (no #)
BLANK=00000000
CLEAR=ffffff22
DEFAULT=e78a4e
TEXT=d4be98
INPUT=d4be98
WRONG=ea6962
VERIFYING=a9b665

swaylock \
  --screenshots \
  --effect-blur=8x5 \
  \
  --inside-ver-color=$CLEAR \
  --ring-ver-color=$VERIFYING \
  \
  --inside-wrong-color=$CLEAR \
  --ring-wrong-color=$WRONG \
  \
  --inside-color=$BLANK \
  --ring-color=$DEFAULT \
  --line-color=$BLANK \
  --separator-color=$DEFAULT \
  \
  --text-color=$TEXT \
  --text-ver-color=$TEXT \
  --text-wrong-color=$TEXT \
  --bs-hl-color=$INPUT \
  --key-hl-color=$INPUT \
  \
  --clock \
  --indicator \
  --timestr="%H:%M:%S" \
  --datestr="%A, %Y-%m-%d"
